name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore lettuceai.jks \
            -alias testing \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "testingtesting69420" \
            -keypass "testingtesting69420" \
            -dname "CN=LettuceAI, OU=Dev, O=LettuceAI, L=Unknown, ST=Unknown, C=US"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: lettuceai-keystore
          path: lettuceai.jks
          retention-days: 1
